### PR TITLE
Quality Of Life Changes

### PR DESCRIPTION
**Pull request by Zaid-maker**

### CODE REVIEW

**Comment by MattA-Official** [comment]
I will review this in a few days. Sorry for the delay; I'm on holiday.

**Comment by Zaid-maker** [comment]
> I will review this in a few days. Sorry for the delay; I'm on holiday.

No problem man :)

**Comment by MattA-Official** [comment]
I would love to accept and merge this pull request. However, it is bundled with some unnecessary changes. Please revise the changes in a future pull request. Please avoid altering the `package-lock.json` file or including it in the `.gitignore` as we want to guarantee the correct dependencies are installed by everyone. 

I love the logo and fixing the missing full stop (period) in `README.md` however "Controling" is not a word and makes the section title incorrect. The alteration you made to the first sentence in that section is grammatically incorrect as it now has two subjects; the "work" and the "changes". In this context, "bugfix" should stay as one word. 

As far as I can see, there was no reason to change the `package.json` as no dependencies were added, removed, or updated.

Including comments in `.example.env` is a brilliant idea that should be included. However, due to the previously mentioned reasons, it cannot be merged as part of this pull request. 

I hope you will be able to contribute to the project again in the future.

<hr>

MattA#6011
Dmod Core Team

**Comment by Zaid-maker** [comment]
No problem man I will do my best next time :)

**Pull request closed without merging**
